sudo: required
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-29
    - extra-android-m2repository
before_script:
  - yes | sdkmanager "platforms;android-29"
    #- chmod +x gradlew
script:
  #- ./gradlew build --stacktrace
  - ./gradlew build connectedCheck